### ISSUE TITLE
Add +20 kts to VCLB, VFRI when anti-ice on

### ISSUE THREAD

**Issue by andydeforest** [Baldstrom/Q400-Performance-Calculator#1]
Hello,

Great little tool here. One thing I would suggest is adding 20 kts to VCLB and VFRI per the manual:

> When flying in icing conditions: Above 400ft AGL, add 20 kts to VFRI Add 20 kts to V CLM

Not going to make a pull request, but changing line 96 of `Computation/Q400Computation.cs` to this would fix it:

`if (Values.AntiIce) { NewOutput.V2 += 20; NewOutput.VCLB += 20; NewOutput.VFRI += 20; }`

**Comment by Baldstrom** [comment]
This has been updated in version v1.0.1
